# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c112bf509d6b0337e6379d61ccb53a8a72a10cc9836fa0ec5540e5f7be7268c44bf3a8ae8bbeffce5f6c39b8dbb740a4557ee0c5a29233074e95ca87460307a8

test:
  secret_key_base: 0fb7f81a356aecc07a18e9526d7ddc318236b8cf9972d247eaef1ef779927b66f580a8dc8f2e8849a8bc539b31d2acd5dba5e3f600655e9f21802346a9ec3537

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
